language: node_js
node_js: "stable"

before_install:
  - stty cols 80

install:
  - npm install testcafe

dist: trusty
sudo: required

env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
    apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable 
  #apt:
  #  sources:
  #   - google-chrome
  #  packages:
  #   - google-chrome-stable
     
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

notifications:
  email:
    recipients:
      - anthonyklinga@gmail.com
    on_success: always # default: change
    on_failure: always # default: always